export function initializeCareerUnlocked(submitForm, redirectToThankYou) {
var WA='919890004828', VENUE='TEONOX Campus, Kothrud, Pune', NEXT='Saturday, 10 Oct 2026';
function wa(m){return 'https://wa.me/'+WA+'?text='+encodeURIComponent(m)}
document.getElementById('waFloat').href=wa("Hi Teonox, I'd like to know more about Career Unlocked.");
document.getElementById('waBook').href=wa('Hi Teonox, I want to book a seat for Career Unlocked ('+NEXT+', '+VENUE+').');
document.getElementById('waQuestion').href=wa('Hi Teonox, I have a question about the Career Unlocked workshop ('+NEXT+', '+VENUE+').');
document.getElementById('parentShare').href='https://wa.me/?text='+encodeURIComponent('Career Unlocked by Teonox — a 90-minute workshop on Business, Digital Marketing & AI careers. '+NEXT+', '+VENUE+'. ₹99. '+location.href);

/* data */
var confusion=["Everyone's doing an MBA. Should I?",'Is digital marketing just posting on Instagram?','Will AI take the job before I even get one?',"I'm doing BCom, but what job does it actually lead to?","My parents want a safe job. I want one I'll enjoy.","I've watched 50 career videos and I'm more confused."];
var routes=[
{t:'Marketing job',w:'Run social, content, SEO or campaigns for a brand or agency; grow into manager and head-of-growth roles.',e:'Monthly salary that rises with results',hot:0},
{t:'Performance marketer',w:'Run Meta and Google ads that bring a brand leads and sales, and prove it in numbers.',e:'Salary, or a retainer plus a share of ad spend',hot:1},
{t:'Freelancer with multiple clients',w:'Handle marketing for 3–6 brands at once, alongside college or full-time.',e:'A monthly retainer from each client',hot:1},
{t:'AI-powered marketer',w:'Use AI to produce content, ads, automations and reports in a fraction of the time.',e:'Retainers plus AI setup projects',hot:0},
{t:'Agency / Business Builder',w:'Build a team, sign clients, sell services or your own products.',e:'Business profit',hot:0},
{t:'Global remote marketer',w:'Work for brands in the US, UK, UAE or Australia without leaving India.',e:'Paid in dollars, pounds or dirhams',hot:0}];
var earn=[{s:'First client',w:'One channel for a local business, part-time',f:'₹10,000–₹30,000 per client / month',ex:'1 client at ₹15,000 = ₹15,000',a:'₹15,000',h:18,hot:0},{s:'Multiple clients',w:'Social and ads for several small brands',f:'₹10,000–₹30,000 per client / month',ex:'4 clients at ₹25,000 = ₹1,00,000',a:'₹1,00,000',h:66,hot:1},{s:'Specialist',w:'Performance marketing with proven results',f:'₹35,000–₹1,00,000 per client / month',ex:'3 clients at ₹50,000 = ₹1,50,000',a:'₹1,50,000',h:96,hot:0},{s:'Global client',w:'Meta ads for an overseas brand',f:'$15–$40 an hour, $25 median',ex:'40 hours at $25 = $1,000 ≈ ₹96,000',a:'₹96,000',h:60,hot:0}];
var scope=[{t:'Performance marketing',d:'Become the person brands trust with their ad money',s:['Meta Ads','Google Ads','YouTube ads','Audience targeting','Ad creatives that convert','Pixels and tracking','CPL and ROAS maths','Scaling budgets'],f:1},{t:'Digital marketing',d:'Bring brands attention, leads and sales across every channel',s:['SEO','Social media and content','Reels strategy','Influencer marketing','Email and WhatsApp marketing','Landing pages','GA4 analytics'],f:0},{t:'AI for marketing',d:'Do in hours what took days, and sell AI services on top',s:['ChatGPT and Claude for content and research','AI image and video tools','Chatbots','Workflow automation','AI-assisted reporting'],f:0},{t:'Business',d:'Turn skills into clients, and clients into long-term retainers',s:['How companies make money','Pricing your services','Proposals and pitching','Client handling','Negotiation','Personal branding','Starting a freelance practice or agency'],f:0}];
var outcomes=[{t:'The full opportunity map',d:'Jobs, performance marketing, freelancing, AI roles, agencies and global work — on one page.'},{t:'How marketers really earn',d:'Retainers, multiple clients and international rates, explained with real numbers.'},{t:'A first hands-on try',d:'Business, marketing and AI through live exercises in the room.'},{t:'Which route fits you',d:'A short self-assessment that points you at the path suits your situation.'},{t:'A personal 90-day plan',d:'What to learn first, and how to land your first client or role.'},{t:'Straight answers',d:'An open Q&A with practitioners who do this for a living.'}];
var kit=['Opportunity Map of routes, roles and earning models','Self-assessment scorecard','90-day plan template','"First client" checklist','Starter list of free AI tools'];
var agenda=[{time:'0–10 min',t:'Unlock',d:'Why skills, not just degrees, decide what you earn — with a live hands-up poll.'},{time:'10–25 min',t:'The opportunity map',d:'Six routes across Business, Digital Marketing and AI, in India and abroad.'},{time:'25–40 min',t:'Performance marketing live',d:'The "Sell me this" challenge, then how a real ad campaign turns spend into sales.'},{time:'40–50 min',t:'AI in action',d:'Watch AI handle a marketer\u2019s task, then try it yourself.'},{time:'50–65 min',t:'The earning maths',d:'How retainers, multiple clients and global clients add up.'},{time:'65–80 min',t:'Your fit',d:'Self-assessment and your 90-day plan.'},{time:'80–90 min',t:'Open floor',d:'Ask anything, plus next steps.'}];
var forYou=["You've finished Class 12 and are choosing a degree or course","You're in BBA, BCom, BMS, BA, BSc or BCA and want skills that earn alongside your degree","You're a fresh graduate weighing a job, an MBA, freelancing or a switch into marketing",'You want to work with clients in India and abroad'];
var notFor=['You want to become an AI/ML engineer or software developer — this is applied AI for business','You expect guaranteed income or a job from a 90-minute session',"You're looking for a get-rich-quick shortcut — earning here takes skill and steady work",'You want to sit back and watch a lecture'];
var office=[{src:'/career-unlocked/media/office/office-1.webp',alt:'Teonox campus — session hall'},{src:'/career-unlocked/media/office/office-2.webp',alt:'Teonox campus — workspace'},{src:'/career-unlocked/media/office/office-3.webp',alt:'Teonox campus — collaboration area'},{src:'/career-unlocked/media/office/office-4.webp',alt:'Teonox campus — learning zone'},{src:'/career-unlocked/media/office/office-5.webp',alt:'Teonox campus — studio corner'},{src:'/career-unlocked/media/office/office-6.webp',alt:'Teonox campus — reception'}];
var brands=[{src:'/career-unlocked/media/brands/flipkart.jpg',n:'Flipkart'},{src:'/career-unlocked/media/brands/reliace.jpg',n:'Reliance'},{src:'/career-unlocked/media/brands/damac.jpg',n:'DAMAC'},{src:'/career-unlocked/media/brands/Gera.jpg',n:'Gera'},{src:'/career-unlocked/media/brands/vtp.jpg',n:'VTP'},{src:'/career-unlocked/media/brands/kohinoor.jpg',n:'Kohinoor'},{src:'/career-unlocked/media/brands/bni.jpg',n:'BNI'},{src:'/career-unlocked/media/brands/Kumar.jpg',n:'Kumar'},{src:'/career-unlocked/media/brands/mantra.jpg',n:'Mantra'},{src:'/career-unlocked/media/brands/maccia.jpg',n:'Maccia'},{src:'/career-unlocked/media/brands/vilas.jpg',n:'Vilas'},{src:'/career-unlocked/media/brands/aw.jpg',n:'AW'},{src:'/career-unlocked/media/brands/a2-digital.jpg',n:'A2 Digital'}];
var tools=[{src:'/career-unlocked/media/tools/chatgpt.webp',n:'ChatGPT'},{src:'/career-unlocked/media/tools/canva.png',n:'Canva'},{src:'/career-unlocked/media/tools/meta.webp',n:'Meta'},{src:'/career-unlocked/media/tools/googleads.jpeg',n:'Google Ads'},{src:'/career-unlocked/media/tools/googleanalytics.png',n:'Google Analytics'},{src:'/career-unlocked/media/tools/WordPress_blue_logo.svg.webp',n:'WordPress'}];
var videos=['/career-unlocked/media/video/video-1.mp4','/career-unlocked/media/video/video-2.mp4','/career-unlocked/media/video/video-3.mp4','/career-unlocked/media/video/video-4.mp4','/career-unlocked/media/video/video-5.mp4','/career-unlocked/media/video/video-6.mp4'];var posters=['/career-unlocked/media/video/poster-1.jpg','/career-unlocked/media/video/poster-2.jpg','/career-unlocked/media/video/poster-3.jpg','/career-unlocked/media/video/poster-4.jpg','/career-unlocked/media/video/poster-5.jpg','/career-unlocked/media/video/poster-6.jpg'];
var proof=[{src:'/career-unlocked/media/proof/meta-1.jpg',tag:'Meta',logo:'/career-unlocked/media/tools/si-meta.svg',ch:'adsmanager.facebook.com / ad sets',ti:'30 ad sets live — reach, frequency and cost per lead'},{src:'/career-unlocked/media/proof/meta-2.jpg',tag:'Meta',logo:'/career-unlocked/media/tools/si-meta.svg',ch:'adsmanager.facebook.com / campaigns',ti:'Nine campaigns — ₹1.98L spent, results by campaign'},{src:'/career-unlocked/media/proof/meta-3.jpg',tag:'Meta',logo:'/career-unlocked/media/tools/si-meta.svg',ch:'adsmanager.facebook.com / ad sets',ti:'8 ad sets — ₹1.77L spent, cost per lead from ₹128'},{src:'/career-unlocked/media/proof/gads-1.jpg',tag:'Google Ads',logo:'/career-unlocked/media/tools/si-googleads.svg',ch:'ads.google.com / campaigns',ti:'₹4.95L spent — 32,118 conversions, 1.26L clicks'},{src:'/career-unlocked/media/proof/gads-2.jpg',tag:'Google Ads',logo:'/career-unlocked/media/tools/si-googleads.svg',ch:'ads.google.com / campaigns',ti:'₹23.3L lifetime spend — 12.5 crore impressions'},{src:'/career-unlocked/media/proof/gads-3.jpg',tag:'Google Ads',logo:'/career-unlocked/media/tools/si-googleads.svg',ch:'ads.google.com / overview',ti:'₹3.55L spent — 5,620 conversions at ₹2.79 CPC'},{src:'/career-unlocked/media/proof/gsc-1.jpg',tag:'SEO',logo:'/career-unlocked/media/tools/si-googlesearchconsole.svg',ch:'search.google.com/search-console',ti:'1.8K clicks, 233K impressions over three months'},{src:'/career-unlocked/media/proof/gsc-2.jpg',tag:'SEO',logo:'/career-unlocked/media/tools/si-googlesearchconsole.svg',ch:'search.google.com/search-console',ti:'6.47K clicks, 379K impressions, 1.7% CTR'},{src:'/career-unlocked/media/proof/gsc-3.jpg',tag:'SEO',logo:'/career-unlocked/media/tools/si-googlesearchconsole.svg',ch:'search.google.com/search-console',ti:'5.18K clicks — average position 7.3 in search'},{src:'/career-unlocked/media/proof/ga-1.jpg',tag:'Analytics',logo:'/career-unlocked/media/tools/si-googleanalytics.svg',ch:'analytics.google.com / traffic acquisition',ti:'Traffic acquisition — sessions by channel, 28 days'},{src:'/career-unlocked/media/proof/ga-2.jpg',tag:'Analytics',logo:'/career-unlocked/media/tools/si-googleanalytics.svg',ch:'analytics.google.com / traffic acquisition',ti:'Organic search leading the daily session mix'},{src:'/career-unlocked/media/proof/ga-3.jpg',tag:'Analytics',logo:'/career-unlocked/media/tools/si-googleanalytics.svg',ch:'analytics.google.com / traffic acquisition',ti:'Long-window trend — five months of channel data'}];
var faqs=[{q:'Can I really earn in lakhs from digital marketing?',a:'Many marketers do, through a salary, multiple clients or both. It takes skill, results and time; the workshop shows the real path and real market rates, not shortcuts.'},{q:'Can I freelance while still in college?',a:'Yes — most start with one small client part-time. The workshop covers how to land the first one.'},{q:'Can I get international clients without experience abroad?',a:'Overseas clients hire on results and communication, not where you studied. You will see where global work comes from and what to show first.'},{q:'Is this a sales pitch for a course?',a:'Teonox runs it and will briefly share its program at the end. The 90 minutes are about your clarity, with no pressure to enrol.'},{q:"I'm in Class 12 or first year. Is it too early?",a:"No — it's the cheapest time to choose well."},{q:"I'm from science or arts. Can I come?",a:'Yes. All three areas are open to any stream.'},{q:'Do I need a laptop or prior knowledge?',a:'No knowledge needed; bring a phone.'},{q:'What does ₹99 cover?',a:'₹99 confirms your seat for the full 90-minute live workshop. It includes entry, the take-home kit, open Q&A and a completion certificate.'},{q:'Can my parents come?',a:'Parents are welcome at the final Q&A. Tell us while booking so we can plan the seating.'},{q:'Will I get a certificate?',a:'Yes — a digital certificate you can share on LinkedIn and Instagram.'},{q:"What if I can't make my date?",a:'Free reschedule if you tell us 24 hours before. After that, the seat passes to a waitlisted attendee.'},{q:'Where is it? Is there an online option?',a:'In person at '+VENUE+'. The first batches are in-person — exercises and trust land better in a room.'}];

function el(h){var d=document.createElement('div');d.innerHTML=h.trim();return d.firstChild}
/* render static lists */
document.getElementById('confusion').innerHTML=confusion.map(function(q,i){return '<div class="p-4 rounded-2xl border '+(i%2?'bg-[#FFE9D6] border-[#FFC79A] ml-auto':'bg-[#FFFDF9] border-[#EADFD0]')+' max-w-[92%]"><p class="font-medium text-sm sm:text-base">“'+q+'”</p></div>'}).join('');
document.getElementById('routes').innerHTML=routes.map(function(c){return '<div class="rounded-3xl p-5 border min-h-[228px] flex flex-col justify-between '+(c.hot?'bg-gradient-to-b from-[#FFE9D6] to-[#FFF3E8] border-[#FF6B1A]':'bg-[#FFFDF9] border-[#EADFD0]')+'"><h3 class="font-display font-extrabold">'+c.t+'</h3><p class="text-xs text-[#6B5E53] mt-1">'+c.w+'</p><p class="text-[11px] font-bold text-[#E24A0B] uppercase mt-4 pt-3 border-t border-dashed border-[#E2D5C2]">● '+c.e+'</p></div>'}).join('');
document.getElementById('earnDesk').innerHTML=earn.map(function(r){return '<div class="grid grid-cols-12 gap-4 items-center rounded-2xl border p-4 '+(r.hot?'bg-gradient-to-r from-[#FFE9D6] to-[#FFF3E8] border-[#FF6B1A]':'bg-[#FFFDF9] border-[#EADFD0]')+'"><div class="col-span-3 font-display font-extrabold">'+r.s+'</div><div class="col-span-4 text-sm text-[#6B5E53]">'+r.w+'</div><div class="col-span-2 text-sm font-bold">'+r.f+'</div><div class="col-span-3 text-sm font-bold text-[#E24A0B]">'+r.ex+'</div></div>'}).join('');
document.getElementById('earnMob').innerHTML=earn.map(function(r){return '<div class="rounded-2xl border p-4 '+(r.hot?'bg-gradient-to-r from-[#FFE9D6] to-[#FFF3E8] border-[#FF6B1A]':'bg-[#FFFDF9] border-[#EADFD0]')+'"><div class="flex justify-between gap-2 mb-2"><span class="font-display font-extrabold">'+r.s+'</span><span class="text-xs font-bold text-[#E24A0B]">'+r.ex+'</span></div><p class="text-xs text-[#6B5E53]">'+r.w+'</p><p class="text-xs font-bold mt-1.5">'+r.f+'</p></div>'}).join('');
document.getElementById('stairs').innerHTML=earn.map(function(s){return '<div class="text-center"><div class="h-32 sm:h-44 flex items-end"><div class="w-full rounded-t-xl '+(s.hot?'bg-gradient-to-t from-[#E24A0B] to-[#FF6B1A]':'bg-gradient-to-t from-[#1E1611] to-[#4A3728]')+'" style="height:'+s.h+'%"></div></div><p class="mt-3 font-display font-black text-xs sm:text-base '+(s.hot?'text-[#E24A0B]':'')+'">'+s.a+'</p><p class="text-[10px] sm:text-xs text-[#6B5E53] font-bold">'+s.s+'</p></div>'}).join('');
document.getElementById('tools').innerHTML=tools.map(function(t){return '<span class="flex items-center gap-2 bg-[#FAF6EF] border border-[#EADFD0] rounded-2xl px-3 py-2"><img src="'+t.src+'" alt="'+t.n+'" class="h-6 sm:h-7 w-auto" loading="lazy" /><span class="text-xs font-bold">'+t.n+'</span></span>'}).join('');
var openScope=0;
function renderScope(){document.getElementById('scope').innerHTML=scope.map(function(a,idx){var o=openScope===idx;return '<div class="rounded-3xl overflow-hidden border '+(a.f?'bg-gradient-to-r from-[#FFFDF9] to-[#FFF6EE] border-[#FF6B1A] border-2':'bg-[#FFFDF9] border-[#EADFD0]')+'"><button data-scope="'+idx+'" class="w-full text-left p-4 sm:p-5 flex items-center justify-between gap-4 min-h-[56px]"><span class="font-display font-extrabold">'+a.t+(a.f?' <span class="text-[10px] font-bold uppercase bg-[#FF6B1A] text-white px-2 py-1 rounded-full ml-2">Most paid-for skill</span>':'')+'</span><span class="text-[#FF6B1A] font-bold">'+(o?'−':'+')+'</span></button>'+(o?'<div class="px-4 pb-5 border-t border-[#EADFD0]/60 pt-3"><p class="text-sm font-bold text-[#E24A0B]">'+a.d+'</p><div class="flex flex-wrap gap-2 mt-2">'+a.s.map(function(s){return '<span class="bg-[#FFE9D6] rounded-full px-3 py-1 text-xs">'+s+'</span>'}).join('')+'</div></div>':'')+'</div>'}).join('');
document.querySelectorAll('[data-scope]').forEach(function(b){b.onclick=function(){openScope=openScope===+b.dataset.scope?-1:+b.dataset.scope;renderScope()}})}
renderScope();
document.getElementById('outcomes').innerHTML=outcomes.map(function(o){return '<div class="bg-[#FFFDF9] border border-[#EADFD0] rounded-3xl p-4"><h3 class="font-display font-extrabold text-sm sm:text-base mb-1">'+o.t+'</h3><p class="text-xs text-[#6B5E53]">'+o.d+'</p></div>'}).join('');
document.getElementById('kit').innerHTML=kit.map(function(k,i){return '<div class="flex items-center gap-3 bg-white/5 border border-[#6A4A33] rounded-2xl px-3.5 py-3"><span class="w-7 h-7 rounded-lg bg-[#FF6B1A] text-white text-[11px] font-black flex items-center justify-center">'+(i+1)+'</span><span class="text-xs sm:text-sm text-[#FFE9D6]">'+k+'</span></div>'}).join('');
document.getElementById('agendaList').innerHTML=agenda.map(function(a){return '<div class="relative"><span class="absolute -left-[18px] sm:-left-[26px] top-5 w-3 h-3 rounded-full bg-[#FF6B1A] ring-4 ring-[#F4ECE0]"></span><div class="bg-[#FFFDF9] border border-[#EADFD0] rounded-3xl p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center gap-3"><span class="text-[11px] font-bold px-3 py-1.5 rounded-full bg-[#FFE9D6] border border-[#FFC79A] text-[#E24A0B] w-fit">⏱ '+a.time+'</span><span><span class="block font-display font-extrabold text-sm sm:text-base">'+a.t+'</span><span class="block text-xs sm:text-sm text-[#6B5E53]">'+a.d+'</span></span></div></div>'}).join('');
document.getElementById('forYou').innerHTML=forYou.map(function(x){return '<li class="flex gap-2.5"><span class="text-[#FF6B1A] font-bold">✓</span><span>'+x+'</span></li>'}).join('');
document.getElementById('notFor').innerHTML=notFor.map(function(x){return '<li class="flex gap-2.5"><span class="font-bold">✕</span><span>'+x+'</span></li>'}).join('');
var openFaq=-1;
function renderFaq(){document.getElementById('faqList').innerHTML=faqs.map(function(f,i){var o=openFaq===i;return '<div class="bg-[#FFFDF9] border rounded-2xl overflow-hidden '+(o?'border-[#FF6B1A]/70':'border-[#EADFD0]')+'"><button data-faq="'+i+'" class="w-full text-left p-4 sm:p-5 flex items-center justify-between gap-4 font-bold text-sm sm:text-base min-h-[48px]"><span>'+f.q+'</span><span class="text-[#FF6B1A]">'+(o?'−':'+')+'</span></button>'+(o?'<div class="px-4 pb-4 text-xs sm:text-sm text-[#6B5E53] border-t border-[#EADFD0]/60 pt-2">'+f.a+'</div>':'')+'</div>'}).join('');
document.querySelectorAll('[data-faq]').forEach(function(b){b.onclick=function(){openFaq=openFaq===+b.dataset.faq?-1:+b.dataset.faq;renderFaq()}})}
renderFaq();
document.getElementById('brandGrid').innerHTML=brands.map(function(b){return '<span title="'+b.n+'" class="w-[140px] h-[90px] rounded-2xl border border-[#EADFD0] bg-white overflow-hidden flex items-center justify-center"><img src="'+b.src+'" alt="'+b.n+'" class="w-full h-full object-contain p-4" loading="lazy" /></span>'}).join('');

/* generic slider */
function makeSlider(trackId,dotsId,renderCard,items,perViewFn,autoMs){
var track=document.getElementById(trackId),pos=0,timer=null;
function pv(){var w=innerWidth;return perViewFn(w)}
function per(){return pv()}
function total(){return Math.max(1,Math.ceil(items.length/per()))}
function draw(){
var p=per(),gap=parseFloat(getComputedStyle(track).gap)||24;
track.innerHTML=items.map(function(it,i){return renderCard(it,i,p,gap)}).join('');
var first=track.children[0];
var step=first?first.getBoundingClientRect().width+gap:0;
track.style.transform='translateX(-'+(pos*step)+'px)';
if(dotsId){var d=document.getElementById(dotsId);if(d){d.innerHTML='';for(var i=0;i<total();i++){var b=document.createElement('button');b.className='h-2.5 rounded-full '+(i===pos?'w-7 bg-[#FF6B1A]':'w-2.5 bg-[#D3C0A6]');b.setAttribute('aria-label','Go to slide '+(i+1));(function(i){b.onclick=function(){pos=i;restart();draw()}})(i);d.appendChild(b)}}}
bindVideos();
}
function restart(){if(timer)clearInterval(timer);if(autoMs)timer=setInterval(function(){pos=(pos+1)%total();draw()},autoMs)}
bindNav(trackId,posSet);function posSet(d){pos=((pos+d)%total()+total())%total();restart();draw()}
draw();restart();
addEventListener('resize',draw);
return{go:posSet};
function bindVideos(){track.querySelectorAll('video').forEach(function(v){v.onclick=function(){if(v.paused){track.querySelectorAll('video').forEach(function(o){if(o!==v)o.pause()});v.play()}else v.pause()}})}
}
function bindNav(trackId,fn){
document.querySelectorAll('[data-pslider]').forEach(function(b){if(trackId==='proofTrack')b.onclick=function(){proofApi.go(+b.dataset.pslider)}});
document.querySelectorAll('[data-gal]').forEach(function(b){if(trackId==='galTrack')b.onclick=function(){galApi.go(+b.dataset.gal)}});
document.querySelectorAll('[data-brand]').forEach(function(b){if(trackId==='brandTrack')b.onclick=function(){brandApi.go(+b.dataset.brand)}});
document.querySelectorAll('[data-vid]').forEach(function(b){if(trackId==='vidTrack')b.onclick=function(){vidApi.go(+b.dataset.vid)}});
}
var proofApi=makeSlider('proofTrack','proofDots',function(s,i,p,gap){return '<div class="rounded-[24px] bg-[#FFFDF9] border border-[#EADFD0] overflow-hidden" style="flex:0 0 calc((100% - '+(p-1)*gap+'px)/'+p+')"><div class="flex items-center gap-2 px-3 py-3 border-b border-[#EADFD0]"><span class="flex gap-1.5"><span class="w-2.5 h-2.5 rounded-full bg-[#FF6B5B]"></span><span class="w-2.5 h-2.5 rounded-full bg-[#FFC93C]"></span><span class="w-2.5 h-2.5 rounded-full bg-[#4CD964]"></span></span><span class="flex-1 h-6 rounded-lg bg-[#F1E8DB] border border-[#EADFD0] text-[10px] px-2.5 flex items-center truncate">'+s.ch+'</span></div><img src="'+s.src+'" alt="'+s.ti+'" class="w-full aspect-[16/7] object-cover object-top" loading="lazy" /><div class="flex items-center gap-2 px-3 py-3 border-t border-[#EADFD0]"><span class="bg-[#FF6B1A] text-white rounded-full px-3 py-1.5 text-[10px] font-black">'+s.tag+'</span><span class="font-display font-extrabold text-xs">'+s.ti+'</span></div></div>'},proof,function(w){return w<=1024?1:2},5000);
var galApi=makeSlider('galTrack',null,function(p,i,pp,gap){return '<div class="relative rounded-2xl overflow-hidden border border-[#EADFD0] aspect-[16/10]" style="flex:0 0 calc((100% - '+(pp-1)*gap+'px)/'+pp+')"><img src="'+p.src+'" alt="'+p.alt+'" class="w-full h-full object-cover" loading="lazy" /><span class="absolute bottom-3 left-4 right-4 text-white text-[13px] font-semibold">'+p.alt+'</span></div>'},office,function(w){return w<=480?1:w<=768?2:3},4000);
var brandApi=makeSlider('brandTrack',null,function(b,i,pp,gap){return '<span class="w-full h-[124px] rounded-2xl border border-[#EADFD0] bg-white overflow-hidden flex items-center justify-center" style="flex:0 0 220px"><img src="'+b.src+'" alt="'+b.n+'" class="w-full h-full object-contain p-4" loading="lazy" /></span>'},brands,function(){return 1},3000);
var vidApi=makeSlider('vidTrack','vidDots',function(v,i,p,gap){return '<div class="rounded-3xl bg-[#FFFDF9] border border-[#EADFD0] overflow-hidden" style="flex:0 0 calc((100% - '+(p-1)*gap+'px)/'+p+')"><div class="relative bg-[#1E1611] aspect-[9/16]"><video src="'+v+'" poster="'+posters[i%posters.length]+'" preload="metadata" playsinline class="w-full h-full object-cover"></video><span class="absolute bottom-3 left-3 text-white text-xs font-bold bg-black/50 px-2 py-1 rounded-full">Tap to play</span></div></div>'},videos,function(w){return w<=480?1:w<=768?2:w<=1024?3:4},0);

/* scroll effects */
var prog=document.getElementById('scrollProgress'),sticky=document.getElementById('stickyBar'),toTop=document.getElementById('toTop');
addEventListener('scroll',function(){var t=document.documentElement,tot=t.scrollHeight-t.clientHeight;prog.style.width=(tot>0?(scrollY/tot*100):0)+'%';var show=scrollY>480;sticky.classList.toggle('translate-y-full',!show);toTop.classList.toggle('opacity-0',!(scrollY>500));toTop.classList.toggle('pointer-events-none',!(scrollY>500))},{passive:true});
toTop.onclick=function(){scrollTo({top:0,behavior:'smooth'})};
/* reveal */
var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}})},{threshold:.08});
document.querySelectorAll('[data-reveal]').forEach(function(s){s.classList.add('reveal');io.observe(s)});
/* offline */
function updOff(){var b=document.getElementById('offlineBar'),on=navigator.onLine;b.classList.toggle('hidden',on);b.classList.toggle('flex',!on)}
addEventListener('online',updOff);addEventListener('offline',updOff);updOff();

/* modal */
var modal=document.getElementById('modal'),body=document.getElementById('modalBody'),step='details';
var F={name:'',phone:'',session:'2026-10-10-morning',consent:true,email:'',stage:'Class 12',stream:'BBA',interest:'Not sure',college:'',parent:'No',pay:'upi',sectionName:''};
var sessions=[{id:'2026-10-10-morning',label:'Saturday, 10 Oct 2026 · 11:00 AM – 12:30 PM'},{id:'2026-10-10-evening',label:'Saturday, 10 Oct 2026 · 4:00 PM – 5:30 PM'}];
function saved(){try{return JSON.parse(localStorage.getItem('teonox_career_unlocked_pass'))}catch(e){return null}}
function setBar(n){['bar1','bar2','bar3'].forEach(function(id,i){document.getElementById(id).className='h-1.5 rounded-full '+(n>i?'bg-[#FF6B1A]':'bg-[#EADFD0]')})}
function openModal(){modal.classList.remove('hidden');modal.classList.add('flex');document.body.classList.add('modal-open');var p=saved();if(p){renderPass(p,false)}else{step='details';renderDetails()}}
function closeModal(){modal.classList.add('hidden');modal.classList.remove('flex');document.body.classList.remove('modal-open')}
document.getElementById('modalClose').onclick=closeModal;
modal.addEventListener('click',function(e){if(e.target===modal)closeModal()});
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeModal()});
document.querySelectorAll('[data-book]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();var t=(this.textContent||this.title||'').replace(/\s+/g,' ').trim();F.sectionName=t||'Career Unlocked CTA';openModal()})});
function field(l,h){return '<label class="block text-xs font-bold mb-1.5">'+l+'</label>'+h}
function renderDetails(){
setBar(1);document.getElementById('stepBar').style.display='';document.getElementById('modalTitle').textContent='Book my seat — ₹99';
body.innerHTML='<form id="f1" class="space-y-3.5"><div class="bg-[#FFE9D6]/60 p-3.5 rounded-2xl border border-[#FFC79A] text-xs"><p class="font-bold text-[#E24A0B] mb-1">🎟 Why do we charge ₹99?</p><p>Free seats get booked and skipped. This small commitment keeps the room serious — <b>Entry confirmation is ready after booking.</b></p></div>'
+field('Full name *','<input id="n" required placeholder="e.g. Rahul Sharma" value="'+F.name+'" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm" />')
+field('WhatsApp number *','<input id="p" required placeholder="10-digit mobile" value="'+F.phone+'" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm" />')
+field('Session date & time *','<select id="s" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm">'+sessions.map(function(x){return '<option value="'+x.id+'"'+(F.session===x.id?' selected':'')+'>'+x.label+'</option>'}).join('')+'</select>')
+'<label class="flex items-start gap-2.5 text-xs cursor-pointer"><input type="checkbox" id="c" '+(F.consent?'checked':'')+' class="mt-0.5 w-4 h-4" /><span>Send me WhatsApp updates about this session — confirmation, reminder and venue details. *</span></label>'
+'<button class="w-full min-h-[48px] rounded-2xl bg-gradient-to-r from-[#FF6B1A] to-[#E24A0B] text-white font-bold">Continue to payment →</button><p class="text-[11px] text-center text-[#6B5E53]">Takes under a minute. No spam — only session updates on WhatsApp.</p></form>';
document.getElementById('f1').onsubmit=function(e){e.preventDefault();F.name=document.getElementById('n').value.trim();F.phone=document.getElementById('p').value.trim();F.session=document.getElementById('s').value;F.consent=document.getElementById('c').checked;if(!F.name||!F.phone||!F.consent)return;renderPay()}}
function renderPay(){
setBar(2);
var lbl=(sessions.find(function(x){return x.id===F.session})||sessions[0]).label;
body.innerHTML='<div class="space-y-4"><div class="rounded-2xl border border-[#EADFD0] bg-[#FAF6EF] p-4"><div class="flex justify-between text-sm"><span>Career Unlocked seat ('+lbl+')</span><b>₹99</b></div><div class="flex justify-between text-sm mt-1.5"><span></span><b class="text-[#E24A0B]">− ₹99</b></div><div class="border-t border-dashed border-[#EADFD0] mt-3 pt-3 flex justify-between"><b>Payable now</b><span class="font-display font-black text-xl text-[#E24A0B]">₹99</span></div></div>'
+'<div><label class="block text-xs font-bold mb-1.5">Payment method</label><div class="grid grid-cols-2 gap-3"><button id="upi" class="min-h-[52px] rounded-2xl border px-4 py-3 font-bold text-sm">UPI</button><button id="card" class="min-h-[52px] rounded-2xl border px-4 py-3 font-bold text-sm">Card</button></div></div>'
+'<p class="p-3.5 bg-[#FAF6EF] rounded-2xl border border-[#EADFD0] text-[11px] text-[#6B5E53]">Demo checkout in this static file — connect Razorpay / UPI link here for live payments. The seat is held the moment payment succeeds.</p>'
+'<button id="pay" class="w-full min-h-[48px] rounded-2xl bg-gradient-to-r from-[#FF6B1A] to-[#E24A0B] text-white font-bold">Pay ₹99 & hold my seat →</button>'
+'<button id="back1" class="w-full text-xs text-[#6B5E53]">‹ Back to details</button></div>';
function paint(){document.getElementById('upi').className='min-h-[52px] rounded-2xl border px-4 py-3 font-bold text-sm '+(F.pay==='upi'?'bg-[#FFE9D6] border-[#FF6B1A] text-[#E24A0B]':'bg-[#FAF6EF] border-[#EADFD0]');document.getElementById('card').className='min-h-[52px] rounded-2xl border px-4 py-3 font-bold text-sm '+(F.pay==='card'?'bg-[#FFE9D6] border-[#FF6B1A] text-[#E24A0B]':'bg-[#FAF6EF] border-[#EADFD0]')}
paint();document.getElementById('upi').onclick=function(){F.pay='upi';paint()};document.getElementById('card').onclick=function(){F.pay='card';paint()};
document.getElementById('back1').onclick=renderDetails;
document.getElementById('pay').onclick=function(){this.textContent='Processing ₹99…';var b=this;setTimeout(function(){renderProfile()},700)}}
function renderProfile(){
setBar(3);
body.innerHTML='<form id="f3" class="space-y-3.5"><div class="bg-[#FFE7E0] p-3.5 rounded-2xl border border-[#FFC6B5] text-xs"><p class="font-bold text-[#E24A0B] mb-1">✓ Seat held — ₹99 paid</p><p>Two quick questions so the exercises in the room are tailored to you.</p></div>'
+field('Email address *','<input id="e" type="email" required placeholder="name@email.com" value="'+F.email+'" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm" />')
+field('Current stage *','<select id="st" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm">'+['Class 12','UG year 1–3','Graduate','Working'].map(function(o){return '<option'+(F.stage===o?' selected':'')+'>'+o+'</option>'}).join('')+'</select>')
+field('Stream *','<select id="sm" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm">'+['BBA','BCom','BMS','BA','BSc','BCA','Engineering','Other'].map(function(o){return '<option'+(F.stream===o?' selected':'')+'>'+o+'</option>'}).join('')+'</select>')
+'<div><label class="block text-xs font-bold mb-1.5">Most curious about *</label><div class="flex flex-wrap gap-2" id="ints"></div></div>'
+field('College (optional)','<input id="cl" placeholder="e.g. Fergusson College" value="'+F.college+'" class="w-full min-h-[44px] px-3.5 py-2.5 rounded-xl bg-[#FAF6EF] border border-[#EADFD0] text-sm" />')
+'<button class="w-full min-h-[48px] rounded-2xl bg-gradient-to-r from-[#FF6B1A] to-[#E24A0B] text-white font-bold">Confirm my seat →</button><p class="text-[11px] text-center text-[#6B5E53]">Confirmation with a QR ticket arrives on WhatsApp and email.</p></form>';
var box=document.getElementById('ints');
['Business','Digital Marketing','AI','Not sure'].forEach(function(o){var b=document.createElement('button');b.type='button';b.textContent=o;b.className='min-h-[40px] px-4 py-2 rounded-full text-xs font-bold border '+(F.interest===o?'bg-[#FF6B1A] border-[#FF6B1A] text-white':'bg-[#FAF6EF] border-[#EADFD0]');b.onclick=function(){F.interest=o;Array.prototype.forEach.call(box.children,function(x,i){var on=['Business','Digital Marketing','AI','Not sure'][i]===o;x.className='min-h-[40px] px-4 py-2 rounded-full text-xs font-bold border '+(on?'bg-[#FF6B1A] border-[#FF6B1A] text-white':'bg-[#FAF6EF] border-[#EADFD0]')})};box.appendChild(b)});
document.getElementById('f3').onsubmit=function(e){e.preventDefault();var submitBtn=document.querySelector('#f3 button');if(submitBtn){submitBtn.disabled=true;submitBtn.textContent='Submitting…';}F.email=document.getElementById('e').value.trim();if(!F.email){if(submitBtn){submitBtn.disabled=false;submitBtn.textContent='Confirm my seat →';}return null;}F.stage=document.getElementById('st').value;F.stream=document.getElementById('sm').value;F.college=document.getElementById('cl').value;var p={name:F.name,phone:F.phone,email:F.email,currentStatus:F.stage+' · '+F.stream+' · '+F.interest,sessionId:F.session,sessionLabel:(sessions.find(function(x){return x.id===F.session})||sessions[0]).label,passId:'TNX-CU-'+Math.floor(1000+Math.random()*9000),registeredAt:new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})};var sessionLabel=p.sessionLabel;submitForm('Career Unlocked Workshop',{fullName:F.name,name:F.name,email:F.email,phone:F.phone,location:F.college||'',qualification:'',profile:F.stage+' | '+F.stream,reason:F.interest,source:'career-unlocked',traffic_channel:'career-unlocked',referral:'',page_url:'/career-unlocked',form_type:'Career Unlocked Workshop',section_name:F.sectionName||'Career Unlocked Registration',consent:F.consent?'Yes':'No',sessionId:F.session,sessionLabel:sessionLabel,parent:F.parent||'No'}).then(function(){redirectToThankYou('Career Unlocked');}).catch(function(){if(submitBtn){submitBtn.disabled=false;submitBtn.textContent='Confirm my seat →';}});return null;}}
function renderPass(p,fresh){
document.getElementById('stepBar').style.display='none';document.getElementById('modalTitle').textContent='Your Workshop Pass';document.getElementById('modalSub').textContent='Seat confirmed • Saved on this device';
body.innerHTML=(fresh?'<div class="p-3 bg-[#FFE7E0] border border-[#FFC6B5] rounded-2xl text-xs text-[#E24A0B] font-bold mb-4">✓ Seat confirmed! Your QR ticket is on its way on WhatsApp and email.</div>':'')
+'<div class="rounded-2xl bg-gradient-to-br from-[#1E1611] to-[#34241A] text-white p-5 border border-[#FF6B1A]/40"><p class="text-[10px] font-bold tracking-widest text-[#FF9A3D]">CAREER UNLOCKED · OFFICIAL PASS</p><h4 class="text-2xl font-extrabold font-display">TEONOX</h4><p class="text-xs text-[#FFE9D6]">Business, Digital Marketing & AI — 90-minute workshop</p>'
+'<div class="grid grid-cols-2 gap-3 py-4 text-xs border-t border-b border-white/10 mt-4"><div><p class="text-white/60 text-[10px]">ATTENDEE</p><p class="font-bold text-sm">'+p.name+'</p><p class="text-[#FF9A3D]">'+p.phone+'</p></div><div><p class="text-white/60 text-[10px]">PASS ID</p><p class="font-bold text-sm">'+p.passId+'</p><p class="text-white/70 text-[11px]">'+p.currentStatus+'</p></div><div><p class="text-white/60 text-[10px]">DATE & TIME</p><p class="font-bold">'+p.sessionLabel+'</p></div><div><p class="text-white/60 text-[10px]">VENUE</p><p class="font-bold">'+VENUE+'</p></div></div>'
+'<p class="text-[11px] mt-3 text-white/70">BOOKED ON '+p.registeredAt+' · ₹99 CONFIRMATION · Entry + exit scan</p></div>'
+'<div class="flex gap-3 mt-4"><button id="print" class="flex-1 min-h-[44px] rounded-xl bg-[#FAF6EF] border border-[#EADFD0] font-bold text-sm">Save / Print Pass</button><button id="cancel" class="text-xs underline text-[#6B5E53]">Cancel Pass</button></div>';
document.getElementById('print').onclick=function(){window.print()};
document.getElementById('cancel').onclick=function(){if(confirm('Cancel your reserved pass? Your seat will be released.')){try{localStorage.removeItem('teonox_career_unlocked_pass')}catch(e){}step='details';renderDetails()}}}
}
